issp-center-dev/DCore

python/dcore_check.py, test/check_chain_hubbardI/check_chain_hubbardI.py, test/check_chain_hubbardI_so/check_chain_hubbardI_so.py, test/check_chain_triqsqmc/check_chain_triqsqmc.py, test/check_chain_triqsqmc_so/check_chain_triqsqmc_so.py
dcore_check has been improved.
Changes:
- No plot on X window.
- ``--output`` option deleted (figures are generated by default).
New features:
- The chemical potential is plotted as a function of iteration number.
- The renormalization factor [related to ImSigma(iw_0)] is plotted as a function of iteration number.
- ``--prefix`` option, which specifies filename prefix (default is 'check/').
- ``--ext`` option, whicho specifies file type of figures (default is 'png').
=> Improve dcore_check

python/dmft_core.py, python/impurity_solvers/alps_cthyb.py, python/impurity_solvers/base.py
Removed work_dir from impurity solvers.
=> chcwd is performed outside impurity solvers

python/impurity_solvers/alps_cthyb.py, python/impurity_solvers/alps_cthyb_seg.py, python/impurity_solvers/null_solver.py, python/impurity_solvers/pomerol.py, python/tools.py
Hermitianization is performed in ``extract_H0()`` by default.
=> Perform hermitinization in extract_H0

python/dcore.py, python/impurity_solvers/alps_cthyb.py, python/impurity_solvers/alps_cthyb_seg.py, python/impurity_solvers/pomerol.py, test/alps_cthyb/alps_cthyb.py
Corrected the spin order in impurity solvers
=> Spin order

python/dcore_pre.py, python/dmft_core.py, python/tools.py
As the title says, some error messages have been improved.
Also, a common part is moved to tools.py
=> Improve error message when reading potential matrix is failed

python/dmft_core.py, python/program_options.py
basis_rotation has been disabled by default.
Its type has been changed to str for future extensions.
=> basis_rotation in model section

python/dcore_post.py
``--prefix`` option is introduced in dcore_post. The default value is 'post/', and all results are stored in 'post' directory.
=> prefix option in dcore_post

python/dmft_core.py
* dcore creates an output file if restart == True and an output file does not exist.
* dcore creates an output file if restart == True and an output file does not exist.
=> dcore creates a backup if an output file exists for restart == False.

python/dcore_post.py, python/dmft_core.py
Fixed a minor bug in dcore_post
=> Fixed a bug in dcore_post: dos was not computed for bethe lattice

doc/impuritysolvers/alpscore_ctseg/ctseg.rst, python/impurity_solvers/alps_cthyb_seg.py, python/program_options.py, python/tools.py
This PR includes several update in ALPS/cthyb-seg interface:
- Fixed a bug on chemical potential
- Fixed some warnings
- Updated doc (add explanations on optional parameters)
- Deleted some print for debugging
=> Fix a bug in interface to ALPS/cthyb-seg

python/dcore_check.py, python/program_options.py
- The default range of Matsubara freq has been changed:
If omega_check is not specified, a fixed number of Matsubara points are taken.
- The plot range begins with omega=0.
=> Improve the figure "sigma_ave" in dcore_check

doc/impuritysolvers/alpscore_ctseg/ctseg.rst, python/dcore_check.py, python/dcore_pre.py, python/impurity_solvers/alps_cthyb_seg.py, python/program_options.py, python/tools.py
This release includes a major bugfix for ALPS/cthyb-seg interface.
=> Release 2.0.1b

doc/impuritysolvers/alpscore_ctseg/ctseg.rst, python/impurity_solvers/alps_cthyb_seg.py, python/program_options.py, python/tools.py
Changed the definition of n_tau = n_iw * 2 + 1 in cthyb-seg solver
=> CTHYB-SEG minor fix

doc/tutorial/afm/mk_hr.py, python/dcore_post.py, python/impurity_solvers/alps_cthyb_seg.py
Reverts issp-center-dev/DCore#50
=> Revert "CTHYB-SEG minor fix"

python/sumkdft.py
The title fully describes the modification.
In the previous version, I/O was sometimes frozen in a large cluster system.
=> Read HDF5 file only on the master node

CMakeLists.txt, doc/install_triqs14x.rst, python/program_options.py, tools/w90tool.py
* Fixed wrong description on how to install TRIQS/DFTTools
* CMake checks if DFTTools is installed.
* Fixed a bug in parsing knode
* Fixed a bug in w90tool.py
=> Minor bug fixes

python/tools.py
Fixed a bug in loading self-energy from a HDF file created using triq2
=> Bugfix load self-energy

CMakeLists.txt, doc/CMakeLists.txt, doc/conf.py.in
* In doc, *.dat file are now installed.
* Version bump to 2.0.2
=> Fixed bug: *.dat was not install

python/dmft_core.py
DC correction was not computed correctly when fix_mu = True.
=> Fixed a bug in computing DC correction when fix_mu = True

python/impurity_solvers/pomerol.py
There was a bug in a spin order in the pomerol interface. This resulted in a wrong Sigma(iw) when the magnetic field is applied.
=> Bugfix in pomerol interface

python/dcore.py, python/dcore_bse.py, python/dcore_check.py, python/dcore_post.py, python/dcore_pre.py, python/version.py.in
dcore and dcore_* support "--version" option.
```
> dcore --version
DCore 2.0.2
```
=> Added --version option

python/dmft_core.py
Fixed a bug in which double counting correction is not computed if there are equivalent shells.
=> Fixed a bug for corr_to_inequivalent + dc

python/program_options.py
Use essentially all the Matsubara points for analytic continuation with Pade approximation.
=> Changed default value of omega_pade to a very large number

src/dcore/impurity_solvers/alps_cthyb.py, src/dcore/impurity_solvers/alps_cthyb_seg.py, src/dcore/impurity_solvers/pomerol.py, src/dcore/tools.py
The code that expands exec_path is moved to a function in tools. This function is called from three solvers pomerol, alps_cthyb, alps_cthyb_seg.
=> Expanding exec_path

src/dcore/impurity_solvers/alps_cthyb_seg.py
The spin and orbital indices are exchanged in conversion from CTHYB-SEGMENT results to DCore. This fix affects only when spin_orbit=True.
=> Fix a bug in interface to CTHYB-SEGMENT solver for spin_orbit=True

src/dcore/dcore.py, src/dcore/dcore_bse.py, src/dcore/dcore_check.py, src/dcore/dcore_mpicheck.py, src/dcore/dcore_post.py, src/dcore/dcore_pre.py, src/dcore/dmft_core.py, src/dcore/sumkdft_opt.py, src/dcore/sumkdft_workers/gloc_worker.py
Improvements:
- labels in dcore_check
- error messages when input file does not exist
- performance of dcore_check (plot of iter_sigma-ish?.png)
- error messages when calc_mu fails
A new plot in dcore_check:
- iteration number vs total_chage
=> Improvements on error messages, and a new plot in dcore_check

src/dcore/dcore.py, src/dcore/dcore_bse.py, src/dcore/dcore_check.py, src/dcore/dcore_mpicheck.py, src/dcore/dcore_post.py, src/dcore/dcore_pre.py, src/dcore/dmft_core.py, src/dcore/interaction.py, src/dcore/lattice_models/__init__.py, src/dcore/program_options.py, src/dcore/sumkdft_workers/gloc_worker.py, src/dcore/typed_parser.py
This PR includes several improvement in usability.
- Allow multiple input files
- Print parameters on stdout in the beginning of ``dcore*``
- Delete unnecessary parameters
- Introduce a parameter ``post_dir``
- Improve error messages
- Improve help messages
=> Multiple input files; Print parameters; Introduce a parameter post_dir

examples/highspin_lowspin/README.md, examples/highspin_lowspin/run.sh, examples/square_bse/README.md, examples/square_bse/run.sh, src/dcore/dcore_bse.py, src/dcore/sumkdft_workers/bse_worker.py
``dcore_bse`` and related examples are updated to follow the interface of BSE 0.1.0.
=> Change BSE interface

src/dcore/sumkdft_opt.py
As the title says.
Save memory. No change in results.
=> Each MPI process stores only a part of hopping array

src/dcore/impurity_solvers/hphi.py
To avoid "Error: NonHermite" in HPhi.
=> minor fix in HPhi interface

setup.py, src/dcore/impurity_solvers/alps_cthyb.py
=> Fixed runtime error in ALPS/CT-HYB interface without TRIQS

src/dcore/impurity_solvers/__init__.py, src/dcore/impurity_solvers/jo_cthyb_seg.py, src/dcore/tools.py
Another CTHYB-SEGMENT impurity solver is added.
https://github.com/j-otsuki/cthyb
=> New impurity solver JO/cthyb-seg

.github/workflows/ci_dcorelib.yml, src/dcore/converters/hk.py, src/dcore/converters/wannier90.py, src/dcore/dmft_core.py, src/dcore/impurity_solvers/alps_cthyb.py, src/dcore/impurity_solvers/alps_cthyb_seg.py, src/dcore/impurity_solvers/base.py, src/dcore/impurity_solvers/hphi_spectrum.py, src/dcore/interaction.py, src/dcore/lattice_models/tools.py, src/dcore/openmx2dcore.py, src/dcore/sumkdft_opt.py, src/dcore/sumkdft_post.py, src/dcore/tools.py, tools/respack2wan90.py
* Fix runtimer error when using ALPS/CT-HYB solver without dcorelib
* Update Python, numpy, scipy verions
=> Minor updates

.github/workflows/wheel.yml
=> update upload/download-artifact actions to v4
