- python/lattice_model.py
- python/manip_database.py
- python/program_options.py
- python/sumkdft.py
New mode `lattice = external` is introduced.
This mode allows an input from an externally prepared HDF5 database that includes lattice information.
An example of input parameters is shown below
```
[model]
lattice = external
norb = -9999
nelec = -9999
kanamori = [(2.0, 0.0, 0.0)]
[system]
beta = 10.0
nk = 10
n_iw = 1000
prec_mu = 0.001
```
`norb` and `nelec` are not used in this mode. It is safe to set unreasonable values so that one can easily detect possible bugs.
`nk` should be consistent with the database.
This mode does not support spectrum calculations by `dcore_post`, because it requires radical change of the structure of `dcore_post`.
---
The new file `manip_database.py` will be used later in relation to spin-orbit coupling.
> New mode, lattice = external

- python/typed_parser.py
The ordering of parameters are kept so that the documentation looks nicer. This was done by replacing dict with collections.OrderedDict in TypedParser.
> Keep the ordering of parameters in documentations

- CMakeLists.txt
This change allows us to build doc without TRIQS.
```
cmake \
-DCMAKE_VERBOSE_MAKEFILE=ON \
-DBUILD_DOC=ON \
-DBUILD_DCORE=OFF \
~/PycharmProjects/DCore
```
> Build doc without triqs

- examples/square_bse_sparse/README.md
- examples/square_bse_sparse/dmft_square.in
- examples/square_bse_sparse/info
- examples/square_bse_sparse/qpath.in
- examples/square_bse_sparse/run.sh
- python/sparse_sampling/tools.py
New example for BSE calculations for the Hubbard model on a square lattice using sparse sampling techniques.
The model parameters are the same as those for the existing square_bse example.
> Added example for square_bse_sparse

- Dockerfile
- doc/install.rst
- test/CMakeLists.txt
- test/chain_hubbardI/CMakeLists.txt
- test/chain_hubbardI/dmft.ini.in
- test/chain_hubbardI_so/CMakeLists.txt
- test/chain_hubbardI_so/dmft.ini.in
This fixes failure of mpi-dependent unit tests on sekirei.
One can specify the name of a MPI wrapper to DCore via cmake.
The documentation has been updated accordingly.
> Custom mpirun for test autodoc

- .travis_scripts/deploy_docs.sh
When deploy document of some branch more than once, the latest documents are installed into not `branchname` but `branchname/dcore_doc` .
This PR fixed it (docs are always installed into `branchname` ).
> fixed docs deploy script

- python/dcore_bse.py
- python/impurity_solvers/alps_cthyb.py
- python/impurity_solvers/base.py
- python/impurity_solvers/pomerol.py
``dcore_bse`` saves not only X_loc but also chi_loc, if available.
At present, only pomerol solver supports chi_loc. ``pomerol`` and ``pomerol2dcore`` needs to be updated.
> Pass chi_loc to BSE solver

- python/dcore_check.py
- python/program_options.py
A new parameter ``T`` is added in [system] block. If ``T`` is given, ``beta`` is replaced with 1/T.
> Allow input T instead of beta

- python/impurity_solvers/pomerol.py
The version check in pomerol solver is executed using mpirun command to adapt to some environment (in particular, sekirei).
An update of pomerol2dcore to the latest version, 1.4, is required.
> Adapt pomerol solver to sekirei

- CMakeLists.txt
- doc/CMakeLists.txt
- doc/install.rst
- doc/reference/input.rst
- python/CMakeLists.txt
- python/mpi_command.py.in
- python/program_options.py
- test/bse_sparse/CMakeLists.txt
- test/bse_sparse/sparse_fit.ini.Lambda100
- test/bse_sparse/sparse_fit.ini.ref
- test/chain_hubbardI/CMakeLists.txt
- test/chain_hubbardI/dmft.ini
- test/chain_hubbardI_so/CMakeLists.txt
- test/chain_hubbardI_so/dmft.ini
`cmake -DMPIEXEC=<MPIRUN>` replaces the default value of `mpi.command` with `<MPIRUN>`
> Option for replacing default value of `mpi.command`

- python/dcore_post.py
- python/program_options.py
New parameters ``n_pade_min`` and ``n_pade_max`` are introduced. These bounds the number of Matsubara points used for Pade approximation in the range [n_pade_min: n_pade_max].
> Number of Matsubara points in Pade approximation

- src/dcore/sumkdft_opt.py
If projindex is an array of non-sequential integers,
the old does not work as expected.
This may be problematic when there are several correlated shells.
> Fixed bug in upfold_index in SumkDFT_opt

- src/dcore/impurity_solvers/alps_cthyb_seg.py
- src/dcore/impurity_solvers/base.py
An input like below now works:
```
[impurity_sover]
name = ALPS/cthyb-seg
basis_rotation = Hloc
```
> Support basis_rotation in CTHYB-SEGMENT solver

- src/dcore/dmft_core.py
- src/dcore/fourier.py
- src/dcore/program_options.py
- src/dcore/sumkdft_opt.py
- src/dcore/sumkdft_workers/gloc_worker.py
- src/dcore/tools.py
- tests/non-mpi/fourier/fourier.py
A new parameter ``no_tail_fit`` is introduced in [system] block. The occupation number is computed without tail fitting, if ``no_tail_fit=True`` is specified.
A no-tail-fit Fourier transform is implemented, but not used yet.
> no_tail_fit option

- src/dcore/dmft_core.py
- src/dcore/program_options.py
When the following option is activated, the DC matrix is average over orbitals in each shell.
```
[system]
dc_orbital_average = True
```
The default is False.
> New option dc_orbital_average in [system]

- src/dcore/dcore_bse.py
- src/dcore/dcore_post.py
- src/dcore/dmft_core.py
- src/dcore/sumkdft_workers/gloc_worker.py
The total charge including uncorrelated shells is computed when ``fix_mu=True``.  The result is printed on stdout and stored in **seed.out.h5/dmft_out/total_charge/**.
> Total charge

- src/dcore/_dispatcher.py
To avoid the following error in Python 3.11.5:
```
Traceback (most recent call last):
File "/home/otsuki/venv/python3.11/dcore_e/bin/dcore_pre", line 5, in <module>
from dcore.dcore_pre import run
File "/home/otsuki/gitclones/dcore/src/dcore/dcore_pre.py", line 24, in <module>
from dcore._dispatcher import HDFArchive
File "/home/otsuki/gitclones/dcore/src/dcore/_dispatcher.py", line 22, in <module>
if not importlib.util.find_spec(l):
^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'
```
> Fix import importlib.util

- doc/reference/interaction.rst
- src/dcore/interaction.py
- src/dcore/program_options.py
The interaction tensor U_{abcd} can be given from a file.
```
[model]
interaction = file
interaction_file = ['umat.npy',]
```
NumPy .npy file and a text file are supported.
> [model] interaction=file

- src/dcore/dcore_bse.py
- src/dcore/impurity_solvers/alps_cthyb.py
- src/dcore/impurity_solvers/alps_cthyb_seg.py
- src/dcore/impurity_solvers/base.py
- src/dcore/impurity_solvers/jo_cthyb_seg.py
- src/dcore/impurity_solvers/pomerol.py
- src/dcore/program_options.py
``calc_only_chiloc`` option is introduced in [bse] block. This option is used in SCL and rRPA calculations combined with BSE repo (not published yet).
> [bse]calc_only_chiloc option

- src/dcore/dcore_bse.py
- src/dcore/dcore_post.py
- src/dcore/dcore_pre.py
- src/dcore/program_options.py
- src/dcore/sumkdft_compat.py
- Add new parameters
```
[pre]
flag_lattice = True
flag_umat = True
flag_local_potential = True
overwrite = True
```
- Change HDF5 structure for BSE solver
> skip parameters in dcore_pre

- .github/workflows/ci.yml
- .github/workflows/ci_dcorelib.yml
- .github/workflows/deploy_docs.yml
- .github/workflows/examples.yml
- .github/workflows/examples_dcorelib.yml
- .github/workflows/wheel.yml
New environments are added -- Python 3.11 and Python 3.12.
I found the following;
- Numpy 2.0 does not work (we should fix later)
- Scipy >= 1.13 does not work because of dcore_lib
- Scipy 1.12.0 is not compatible with osqp (this is required by cvxpy?)
So, Numpy 1.26.4 and Scipy 1.11.4 are tested for Python 3.11 and 3.12
> Test on more envs

- .github/workflows/ci.yml
- .github/workflows/examples.yml
- .github/workflows/examples_dcorelib.yml
- bin/deploy_examples.sh
Replace `docker-compose` with `docker compose` (hyphen removed)
ref: https://engineering.nifty.co.jp/blog/26217 (in Japanese) and https://github.com/actions/runner-images/issues/9557
> docker-compose command has been removed from GitHub Actions hosted runner

- doc/install.rst
- src/dcore/_dispatcher.py
~When TRIQS is not installed, `dcorelib.triqs_compat` will be used.~
~If you want to use `dcorelib.triqs_compat` when TRIQS is installed, set an environment variable `DCORE_TRIQS_COMPAT=1`~
By default, use `dcorelib.triqs_compat`.
If you want to use TRIQS library, set an environment variable `DCORE_TRIQS_COMPAT=0` explicitely.
> use dcorelib when triqs is not installed

- src/dcore/anacont/spm.py
- src/dcore/program_options.py
- tests/non-mpi/anacont_spm/anacont_spm.py
The default value of `post.anacont.spm.solver` changes from 'ECOS' to '', which means that cvxpy's default solver will be used because cvxpy stops shipping ECOS from 1.6.
> Use cvxpy's default solver

- doc/analytic_continuation/spm.ini
- doc/reference/input.rst
- src/dcore/anacont/spm.py
- src/dcore/program_options.py
- update reference manuals (input parameters)
- added `[post.anacont.spm.solver]` block
- fix a bug that `[post.anacont.spm.solver]` is ignored when `solver` in `[post.anacont.spm]` is omit (use default CvxPy solver)
> update dcore_anacont spm

- src/dcore/sumkdft_workers/launcher.py
- src/dcore/sumkdft_workers/mpi_main.py
This PR enables DCore to use external workers without modifying DCore source code.
The first argument of `dcore.sumkdft_workers.launcher.run_sumkdft` is a class name of SumkDFT worker.
When the class name is fully qualified, e.g., `mymodule.myclass` the module will be automatically imported.
Otherwise, the class is assumed to belong to `dcore.sumkdft_workers.all_workers` module.
> Enable to call exteral sumkdft class

- setup.py
- src/dcore/_dispatcher.py
- src/dcore/anacont/pade.py
The latest dcorelib (0.9.7) fixes the Pade anacont issue.
`dcore_anacont`  now stops when performing Pade anacont with old dcorelib.
> Pade anacont with dcorelib<0.9.7 gives wrong result
